### ISSUE TITLE
Missing libicudata.so

### ISSUE THREAD

**Issue by Nephos** [gollum/gollum#1088]
Hello,

I got this error from few days, on Archlinux, with ruby 2.2.2

``libicudata.so.55: cannot open shared object file: No such file or directory ``

```text
/home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': libicudata.so.55: cannot open shared object file: No such file or directory - /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.so (LoadError)
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes.rb:1:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gitlab-grit-2.7.3/lib/grit.rb:79:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gollum-grit_adapter-1.0.0/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gollum-grit_adapter-1.0.0/lib/grit_adapter.rb:1:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.3/lib/gollum-lib.rb:12:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gollum-4.0.1/lib/gollum/app.rb:4:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/poulet_a/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gollum-4.0.1/bin/gollum:233:in `<top (required)>'
	from /home/poulet_a/.rbenv/versions/2.2.2/bin/gollum:23:in `load'
	from /home/poulet_a/.rbenv/versions/2.2.2/bin/gollum:23:in `<main>'
```

```sh
>  ls /usr/lib/libicudata.so*
/usr/lib/libicudata.so@  /usr/lib/libicudata.so.56@  /usr/lib/libicudata.so.56.1*
```

Seems to be a problem with the version of the lib.

**Comment by dometto** [comment]
This is not a bug in gollum. I think all you need to do is install the correct, required version of libicudata. There are actually quite a lot of stackoverflow and other threads about this if you google the error you're getting. Most of them pertain to OS X/homebrew but the principle is the same.
