### ISSUE TITLE
Trying to launch gollum fails with error: cannot load such file -- github/markup (LoadError)

### ISSUE THREAD

**Issue by ghecho** [gollum/gollum#1152]
### NOTE: I'm posting this issue (and how I solved it) for those who may encounter it (or a similar one) in the future

I followed the instructions (and yes, `github-markup` was already installed) and try to run `gollum`, then this happened:

~~~ bash
$ gollum
/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- github/markup (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gollum-4.0.1/lib/gollum.rb:8:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/gollum-4.0.1/bin/gollum:7:in `<top (required)>'
	from /usr/local/bin/gollum:23:in `load'
	from /usr/local/bin/gollum:23:in `<main>'
~~~

I tried a bunch of different solutions with no luck, the only thing that worked for me was updating `gem` itself.

~~~ bash
$ gem --version
2.5.0
$ gem update --system
...
bunch of output
...
$ gem --version      
2.6.6
~~~

And then `gollum` works:

~~~ bash
$ gollum
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.6.0 (ruby 2.2.4-p230), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:4567
Use Ctrl-C to stop
^C== Sinatra has ended his set (crowd applauds)
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2016-08-05 23:20:44 -0500 ===
- Goodbye!
~~~

**Comment by bartkamphorst** [comment]
@ghecho Thanks for reporting. What you are describing however is an issue with the Ruby setup on your local machine, not a problem with gollum. I'm therefore closing the issue.

**Comment by ghecho** [comment]
Hi @bartkamphorst , my pleasure.
