### ISSUE TITLE
Gollum 4.1.0: undefined method `last_version' on Ubuntu 16.04

### ISSUE THREAD

**Issue by alexs77** [gollum/gollum#1212]
I installed Gollum 4.1.0 per the instructions at https://github.com/gollum/gollum/wiki/Installation#ubuntu-150415101604 on my Ubuntu 16.04 system. I started it then with just a plain `gollum`, no further options.

When I go to http://localhost:4567/, an error message is displayed:

    NoMethodError at /Home
    undefined method `last_version' for #<Gollum::Page:0x00000001d8de38>

And in the console:

```
$ gollum
[2017-03-28 15:18:05] INFO  WEBrick 1.3.1
[2017-03-28 15:18:05] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
== Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from WEBrick
[2017-03-28 15:18:05] INFO  WEBrick::HTTPServer#start: pid=24967 port=4567
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET / HTTP/1.1" 302 0
- -> /
2017-03-28 15:18:10 - NoMethodError - undefined method `last_version' for #<Gollum::Page:0x00000001d566e0>:
	/var/lib/gems/2.3.0/gems/gollum-4.1.0/lib/gollum/app.rb:532:in `show_page_or_file'
	/var/lib/gems/2.3.0/gems/gollum-4.1.0/lib/gollum/app.rb:515:in `block in <class:App>'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET /Home HTTP/1.1" 500 125382
- -> /Home
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET /__sinatra__/500.png HTTP/1.1" 302 0
http://localhost:4567/Home -> /__sinatra__/500.png
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET /create/__sinatra__/500.png HTTP/1.1" 200 6643
http://localhost:4567/Home -> /create/__sinatra__/500.png
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET /favicon.ico HTTP/1.1" 302 0
http://localhost:4567/Home -> /favicon.ico
127.0.0.1 - - [28/Mar/2017:15:18:10 CEST] "GET /create/favicon.ico HTTP/1.1" 200 6633
http://localhost:4567/Home -> /create/favicon.ico
```

Please see the attached file 
[NoMethodError at _Home.html.txt](https://github.com/gollum/gollum/files/875767/NoMethodError.at._Home.html.txt)
 — it is the HTML generated by Gollum.

Any ideas?

I also tried installing ghe latest github-linguist Gem — didn't change anything.

**Comment by dometto** [comment]
My guess is you don't have a recent version of the `gollum-lib` dependency, in which the `Page#last_version` method was recently introduced. Try a `gem update gollum-lib` and see if it works. If not, please reopen and let us know precisely which version of ruby and gollum's dependencies you're using (`gem list` and `ruby -v`).

**Comment by alexs77** [comment]
You were right, I didn't have a recent version of `gollum-lib` installed; I had installed the Ubuntu package, which wasn't good enough.

Thanks :+1:
