### ISSUE TITLE
SyntaxError rule %r([-\*\+%/~=&\?<>!#@\^]+), Operator

### ISSUE THREAD

**Issue by apeng2012** [gollum/gollum#1230]
gollum@openmediavault:~/wiki$ gollum 
```
/var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge/lexer.rb:362:in `load': /var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge/lexers/abap.rb:220: syntax error, unexpected $undefined (SyntaxError)
        rule %r([-\*\+%/~=&\?<>!#@\^]+), Operator
                                  ^
/var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge/lexers/abap.rb:226: syntax error, unexpected $undefined
        rule %r([-\*\+%/~=&\?<>!#@\^]+), Operator
                                  ^
	from /var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge/lexer.rb:362:in `load_lexer'
	from /var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge.rb:57:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge.rb:56:in `each'
	from /var/lib/gems/1.9.1/gems/rouge-2.0.7/lib/rouge.rb:56:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-lib-4.2.3/lib/gollum-lib/markup.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-lib-4.2.3/lib/gollum-lib.rb:32:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-4.0.1/lib/gollum/app.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-4.0.1/bin/gollum:233:in `<top (required)>'
	from /usr/local/bin/gollum:23:in `load'
	from /usr/local/bin/gollum:23:in `<main>'
```

**Comment by dometto** [comment]
As some easy googling shows, this is an issue with rouge on Ruby <2 that should be solved in the upcoming release of rouge: https://github.com/jneen/rouge/issues/589
