### ISSUE TITLE
Rack usage issue

### ISSUE THREAD

**Issue by karlbateman** [gollum/gollum#1249]
**Versions**
Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
Bundler: 1.12.5
Rackup: Rack 1.3 (Release: 2.0.3)
OS: Fedora 25 amd64

**Steps**
1. Clone the repo with `git clone https://github.com/gollum/gollum ~/`
2. Install the dependencies `cd ~/gollum && bundle install`
3. Modify the `config.ru` file to reflect [the example](https://github.com/gollum/gollum/wiki/Gollum-via-Rack#wiki-body)
4. Run with `bundle exec rackup -p 4567 config.ru`

**Error**
After getting to step 4 above, I get the following error on the console.
```
bundler: failed to load command: rackup (/usr/bin/rackup)
LoadError: cannot load such file -- rdoc
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup/rdoc.rb:2:in `require'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup/rdoc.rb:2:in `<top (required)>'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markups.rb:2:in `require'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markups.rb:2:in `<module:Markup>'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup.rb:102:in `instance_eval'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup.rb:102:in `<module:Markup>'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup.rb:24:in `<module:GitHub>'
  /home/karlbateman/.gem/ruby/gems/github-markup-1.6.0/lib/github/markup.rb:10:in `<top (required)>'
  /home/karlbateman/.gem/ruby/gems/gollum-lib-4.2.5/lib/gollum-lib.rb:17:in `require'
  /home/karlbateman/.gem/ruby/gems/gollum-lib-4.2.5/lib/gollum-lib.rb:17:in `<top (required)>'
  /home/karlbateman/Projects/gollum/lib/gollum/app.rb:4:in `require'
  /home/karlbateman/Projects/gollum/lib/gollum/app.rb:4:in `<top (required)>'
  /home/karlbateman/Projects/gollum/config.ru:15:in `require'
  /home/karlbateman/Projects/gollum/config.ru:15:in `block in <main>'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  /home/karlbateman/Projects/gollum/config.ru:in `new'
  /home/karlbateman/Projects/gollum/config.ru:in `<main>'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/server.rb:300:in `build_app_and_options_from_config'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/server.rb:209:in `app'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/server.rb:337:in `wrapped_app'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/server.rb:273:in `start'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/lib/rack/server.rb:148:in `start'
  /home/karlbateman/.gem/ruby/gems/rack-1.6.8/bin/rackup:4:in `<top (required)>'
  /usr/bin/rackup:23:in `load'
  /usr/bin/rackup:23:in `<top (required)>'
```

Not sure what I am missing here?

**Comment by dometto** [comment]
My guess is there's something wrong with your version of the github-markup
gem, because it's missing the rdoc.rb file. Perhaps you already had the gem
installed and it was modified at some point. Try removing it (gem uninstall
github-markup) and then reinstalling.

**Comment by dometto** [comment]
@karlbateman did you ever get this to work?

**Comment by karlbateman** [comment]
@dometto Not sure what I ended up doing in the end but it worked.
