### ISSUE TITLE
Crash - URI::InvalidURIError 

### ISSUE THREAD

**Issue by markabey** [gollum/gollum#1305]
A wiki page can be crashed by putting this in the contents:

```
```@type:http AND @fields.host:somedomain.com``\`
```
(last backtick escaped to render correctly)

It doesn't occur with single backticks, or when putting the text on a new line after the triple backticks.

Stack trace:
```
[2018-05-02 13:13:11] INFO  WEBrick 1.3.1
[2018-05-02 13:13:11] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
== Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from WEBrick
[2018-05-02 13:13:11] INFO  WEBrick::HTTPServer#start: pid=28619 port=4567
2018-05-02 13:13:12 - URI::InvalidURIError - bad URI(is not URI?): http AND @fields.host:somedomain.com:
        /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split'
        /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
        /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
        /usr/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/remote_code.rb:45:in `req'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/remote_code.rb:31:in `block in extract'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/remote_code.rb:17:in `gsub' 
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/filter/remote_code.rb:17:in `extract'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/markup.rb:120:in `block in process_chain'   
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/markup.rb:119:in `each'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/markup.rb:119:in `process_chain'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/markup.rb:164:in `render'
        /var/lib/gems/2.3.0/gems/gollum-lib-4.2.7/lib/gollum-lib/page.rb:227:in `formatted_data'
        /var/lib/gems/2.3.0/gems/gollum-4.1.2/lib/gollum/app.rb:528:in `show_page_or_file'
        /var/lib/gems/2.3.0/gems/gollum-4.1.2/lib/gollum/app.rb:516:in `block in <class:App>'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route' 
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call' 
        /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.10/lib/rack/handler/webrick.rb:88:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [02/May/2018:13:13:12 BST] "GET /home HTTP/1.1" 500 158005
- -> /home
```
Gollum installed with `sudo gem install gollum` on Ubuntu 16.04
```
gem list | grep gollum
gollum (4.1.2)
gollum-grit_adapter (1.0.1)
gollum-lib (4.2.7)
```

Found this via Gitlab wiki after an upgrade to 10.7. The page didn't use to crash, now it does.

**Comment by bartkamphorst** [comment]
I'm on the `5.x` branch with JRuby and am not seeing this behavior (the string is just rendered with backticks and all). I'll check what happens on ruby 2.4.1 later today.

**Comment by dometto** [comment]
Your block has the precise format of a remote code block, so this is actually expected behavior. If you don't want it to be evaluated as remote code, simply insert a newline after the opening backticks and before the closing backticks.
