### ISSUE TITLE
Help! Gollum via Rack not working

### ISSUE THREAD

**Issue by kzhui125** [gollum/gollum#1309]
here is my config.ru:

```ruby
#!/usr/bin/env ruby
require 'rubygems'
require 'gollum/app'


wiki_options = {:universal_toc => false}
Precious::App.set(:gollum_path, "/home/wiki")
Precious::App.set(:default_markup, :markdown) # set your favorite markup language
Precious::App.set(:wiki_options, wiki_options)
#run Precious::App

require 'rack'

class MapGollum
    def initialize base_path
        @mg = Rack::Builder.new do
            map '/' do
                run Proc.new { [302, { 'Location' => "/#{base_path}" }, []] }
            end
            map "/#{base_path}" do
                run Precious::App
            end
        end
    end

    def call(env)
        @mg.call(env)
    end
end

# Rack::Handler does not work with Ctrl + C. Use Rack::Server instead.
Rack::Server.new(:app => MapGollum.new("/wiki"), :Port => 4567, :Host => '127.0.0.1').start                                                                                                  
```

run `bundle exec rackup config.ru`

`http://127.0.0.1:4567/wiki` was redirected to `http://wiki:4567/`

after ctrl+c

```
[2018-06-03 22:07:42] INFO  WEBrick 1.3.1
[2018-06-03 22:07:42] INFO  ruby 2.5.1 (2018-03-29) [x86_64-linux]
[2018-06-03 22:07:42] INFO  WEBrick::HTTPServer#start: pid=20660 port=4567
^C[2018-06-03 22:07:59] INFO  going to shutdown ...
[2018-06-03 22:07:59] INFO  WEBrick::HTTPServer#start done.
bundler: failed to load command: rackup (/usr/local/bin/rackup)
RuntimeError: missing run or map statement
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:146:in `to_app'
  /home/wiki/gollum/config.ru:44:in `<main>'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `eval'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `new_from_string'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:40:in `parse_file'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:300:in `build_app_and_options_from_config'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:209:in `app'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:337:in `wrapped_app'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:273:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:148:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.10/bin/rackup:4:in `<top (required)>'
  /usr/local/bin/rackup:23:in `load'
  /usr/local/bin/rackup:23:in `<top (required)>'
```
@dometto can you help me, thanks!

**Comment by dometto** [comment]
You should set `base_path` to `'wiki'`, not `'/wiki'`. So try:
```ruby
Rack::Server.new(:app => MapGollum.new("wiki"), :Port => 4567, :Host => '127.0.0.1').start                                                                                                  
```
