### ISSUE TITLE
5.x: uploading with Ace editor does not show drag/drop/uploading CSS

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum#1327]
While test-driving 5.x, I noticed that the editor is no longer visually responsive to [dragging and dropping and uploading](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/css/editor.css#L343-L362). I suspect this has to do with the recent change to the ACE editor. Specifically, I think there must have been a change in the HTML that makes it that [this Javascript](https://github.com/gollum/gollum/blob/master/lib/gollum/public/gollum/javascript/editor/gollum.editor.js#L102-L116) no longer has any effect.

```
Gollum 5.0.1b
Running on: java with Ruby version 2.3.3
Using:
rjgit 5.1.1.0
gollum-rjgit_adapter 0.3.4
gollum-lib 5.0.a.4
With the following renderers:
kramdown 1.17.0
```

**Comment by bartkamphorst** [comment]
@ProgramFan, would you mind investigating? Both the JS and the CSS seem to be loaded, so I suspect it's an issue with `div` ids having changed.

**Comment by bartkamphorst** [comment]
Ping @ProgramFan. 😄

**Comment by ProgramFan** [comment]
I will check it.

**Comment by bartkamphorst** [comment]
Terrific, thank you!

**Comment by ProgramFan** [comment]
It turns out an ajax error when uploading. The error message is 'error' and gives no information. What can be the cause? Any ideas?

**Comment by ProgramFan** [comment]
Gollum prints these errors when uploading:
```
2018-10-28 18:33:38 - NoMethodError - undefined method `tree' for nil:NilClass:
	/usr/local/lib/ruby/gems/2.5.0/gems/gitlab-grit-2.8.2/lib/grit/lazy.rb:31:in `block (2 levels) in lazy_reader'
	/usr/local/lib/ruby/gems/2.5.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:115:in `tree'
	/usr/local/lib/ruby/gems/2.5.0/gems/gollum-lib-5.0.a.4/lib/gollum-lib/committer.rb:45:in `index'
	/usr/local/lib/ruby/gems/2.5.0/gems/gollum-lib-5.0.a.4/lib/gollum-lib/committer.rb:94:in `add_to_index'
	/usr/local/lib/ruby/gems/2.5.0/gems/gollum-5.0.1b/lib/gollum/app.rb:219:in `block (2 levels) in <class:App>'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
	/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
	/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
	/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [28/Oct/2018:18:33:38 CST] "POST /gollum/upload_file HTTP/1.1" 500 138481
http://localhost:4567/gollum/create/Home.md -> /gollum/upload_file
```

The upload_file API has changed?

**Comment by bartkamphorst** [comment]
What kind of file are you trying to upload? Try a basic txt file and see if the issue persists. There are some known issues with uploading (see issue tracker) but I would think these are different from the visuals not appearing.

**Comment by ProgramFan** [comment]
My problem is caused by the bare repository I am testing gollum. After I create the first page, I can upload files. The downside is that there is no visual response. But after the upload finishes, the link will be inserted into the editor. Now I understand that the problem is the drag-and-drop upload works, but without visual response.

**Comment by ProgramFan** [comment]
I find the bug: the new editor body is `gollum-editor-body-ace`, while the css is only defined for `gollum-editor-body`. Change the css works on my side.

**Comment by bartkamphorst** [comment]
That's great! Could you open a PR against the 5x branch with your fix?

**Comment by bartkamphorst** [comment]
Resolved by https://github.com/gollum/gollum/pull/1341.
