### ISSUE TITLE
NoMethodError - undefined method `paged' for #<Gollum::Wiki:47232558598860 /wiki/.git>

### ISSUE THREAD

**Issue by mattydebie** [gollum/gollum#1378]
When pulling gollum on branch 5.x (e0a2b183ad7e7f26675b2ae867f9331527e0ebb3), running `bundle install` and starting Gollum with `bundle exec bin/gollum /wiki` I get the following error:

```
2019-05-02 07:01:46 - NoMethodError - undefined method `paged' for #<Gollum::Wiki:47232558598860 /wiki/.git>
Did you mean?  page
               pages:
	/gollum/lib/gollum/app.rb:517:in `show_page_or_file'
	/gollum/lib/gollum/app.rb:507:in `block in <class:App>'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.0.7/lib/rack/null_logger.rb:9:in `call'
	/usr/local/bundle/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
	/usr/local/bundle/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
	/usr/local/bundle/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/bundle/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
	/usr/local/bundle/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
	/usr/local/bundle/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
```

**Comment by dometto** [comment]
Sorry, `5.x` is not ready for production yet. On 5.x, we're continually updating the `gollum-lib` API, and gollum itself sometimes doesn't keep up. Thanks for pointing this one out!

**Comment by mattydebie** [comment]
No worries! I'm fully aware 5.x is not ready for production yet, just always eager to try out the new stuff :stuck_out_tongue:

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum/pull/1369
