### ISSUE TITLE
5.x: some PDFs break search (because they are searched by content)

### ISSUE THREAD

**Issue by scolytus** [gollum/gollum#1491]
# Problem

* just updated to the latest version from source via my custom docker image
* search functionality was broken, see stacktrace
* investigated a bit, found that `data` in `wiki.rb:499` contained a PDF file's whole content
* I deleted the particular PDF file from the git repo, gollum works fine again
* I have other PDFs in the repo as well, they don't cause this issue
* Found `data  = blob.binary? ? nil : blob.content.force_encoding(enc)` in https://github.com/gollum/rugged_adapter/blob/8f3ea0483a1654a59f2c44f51e80fb833d768814/lib/rugged_adapter/git_layer_rugged.rb#L178
* don't know, maybe `blob.binary?` is broken there?
* Don't have a Ruby dev environment, haven't investigated further

# Example PDF

I can reproduce this issue by having this file in my uploads:
https://download.brother.com/welcome/docp100021/pth105_use_ug_d0123s001_02.pdf

(Yes, that's my label maker :) )

# Stacktrace

```
2020-03-21 15:03:02 - ArgumentError - invalid byte sequence in UTF-8:
	/usr/local/bundle/gems/gollum-lib-5.0.a.4/lib/gollum-lib/wiki.rb:499:in `scan'
	/usr/local/bundle/gems/gollum-lib-5.0.a.4/lib/gollum-lib/wiki.rb:499:in `block in search'
	/usr/local/bundle/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:179:in `block in grep'
	/usr/local/bundle/gems/rugged-0.99.0/lib/rugged/tree.rb:175:in `block in walk_blobs'
	/usr/local/bundle/gems/rugged-0.99.0/lib/rugged/tree.rb:175:in `walk'
	/usr/local/bundle/gems/rugged-0.99.0/lib/rugged/tree.rb:175:in `walk_blobs'
	/usr/local/bundle/gems/gollum-rugged_adapter-0.99.4/lib/rugged_adapter/git_layer_rugged.rb:175:in `grep'
	/usr/local/bundle/gems/gollum-lib-5.0.a.4/lib/gollum-lib/wiki.rb:493:in `search'
	/usr/local/bundle/gems/gollum-5.0.1b/lib/gollum/app.rb:468:in `block (2 levels) in <class:App>'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/null_logger.rb:11:in `call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
	/usr/local/bundle/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:244:in `call'
	/usr/local/bundle/gems/gollum-5.0.1b/bin/gollum:298:in `call'
	/usr/local/bundle/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'
	/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/usr/local/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/usr/local/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

# Gollum Version

Gollum:     `83f4ccfa`
Gollum-Lib: `de56f29`

**Comment by dometto** [comment]
> don't know, maybe blob.binary? is broken there?

That seems very possible, as `.binary?` [uses a heuristic](https://www.rubydoc.info/github/libgit2/rugged/Rugged/Blob#binary%3F-instance_method) that *might* of course fail, sometimes:

> The heuristic used to guess if a file is binary is taken from core git: Searching for NUL bytes and looking for a reasonable ratio of printable to non-printable characters among the first 4000 bytes.

We should see if there is a way of catching the edge case, as we can't do much about the `binary?` method from Rugged.

**Comment by dometto** [comment]
@scolytus any chance you could give the following fix a go locally? The `if`-statement starting at`/usr/local/bundle/gems/gollum-lib-5.0.a.4/lib/gollum-lib/wiki.rb:499` should look like this:

```ruby
          begin
          data.scan(query) do |match|
            result[:context] << match.first
            result[:count] += match.first.scan(/#{search_terms_regex}/i).size
          end
          rescue
            next
          end
```

**Comment by dometto** [comment]
Sorry, overlooked that you provided the file. The fix works. Will open a PR for it ASAP

**Comment by dometto** [comment]
See https://github.com/gollum/gollum-lib/pull/364

**Comment by scolytus** [comment]
@dometto I just tried your code, catching the exception here makes it work for me.

Thanks!

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum-lib/pull/364
