### ISSUE TITLE
Change base_path in rack-compatible server

### ISSUE THREAD

**Issue by yoonbae81** [gollum/gollum#1610]
I'm trying to change base_path in rack-compatible server. 

The last section of [document](https://github.com/gollum/gollum/wiki/Gollum-via-Rack#the---base-path-option) directs to change Precious::App to Precious::MapGollum in the config.ru.
```rb
#!/usr/bin/env ruby
require 'rubygems'
require 'gollum/app'

gollum_path = File.expand_path(File.dirname(__FILE__)) # CHANGE THIS TO POINT TO YOUR OWN WIKI REPO
wiki_options = {:universal_toc => false}
Precious::App.set(:gollum_path, gollum_path)
Precious::App.set(:default_markup, :markdown) # set your favorite markup language
Precious::App.set(:wiki_options, wiki_options)
run Precious::App
```

However, I got errors when I changed all or some of Precious::App to Precious::MapGollum. Could somebody kindly advice me?

**Comment by dometto** [comment]
Have you tried only changing `run Precious::App` to `run Precious::MapGollum`? Please let us know if this works, the wiki page you referred to could use some updating.

**Comment by yoonbae81** [comment]
The rackup starts with the change you've explained, but error occurred when I access the front page. Thanks for your advice in advance.

```
NoMethodError: undefined method `call' for Precious::MapGollum:Class
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/auth/basic.rb:28:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
        /var/lib/gems/2.7.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:231:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
        /var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
        /usr/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by dometto** [comment]
@yoonbae81 did you get it to work? :) Please let us know so we can update the docs

**Comment by yoonbae81** [comment]
No, I gave up to and I moved to Jingo. Sorry for that.

**Comment by acavalin** [comment]
For those wondering how to solve this problem, here is my working solution:

~~~ruby
# config.ru
require 'rubygems'
require 'gollum/app'

sub_dir = 'my-www-sub-folder'

Precious::App.set :wiki_options, { base_path: sub_dir }

run Precious::MapGollum.new(sub_dir)
~~~

@dometto I also updated the [Gollum via Rack](https://github.com/gollum/gollum/wiki/Gollum-via-Rack#the---base-path-option) wiki page

**Comment by dometto** [comment]
Thanks @acavalin!
