### ISSUE TITLE
Cannot execute gollum after "source build"

### ISSUE THREAD

**Issue by nolash** [gollum/gollum#1613]
After build from source instructions complete:

```
gollum $ ./bin/gollum
Traceback (most recent call last):
	5: from ./bin/gollum:7:in `<main>'
	4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /dev/shm/lashtmp/gollum/lib/gollum.rb:8:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- github/markup (LoadError)
gollum $ bundle ./bin/gollum
Could not find command "./bin/gollum".
gollum $ bundle exec ./bin/gollum
bundler: failed to load command: ./bin/gollum (./bin/gollum)
LoadError: cannot load such file -- rdoc
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup/rdoc.rb:2:in `require'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup/rdoc.rb:2:in `<top (required)>'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markups.rb:2:in `require'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markups.rb:2:in `<module:Markup>'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:101:in `instance_eval'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:101:in `<module:Markup>'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:25:in `<module:GitHub>'
  /dev/shm/lashtmp/gollum/vendor/bundle/ruby/2.7.0/gems/github-markup-3.0.4/lib/github/markup.rb:10:in `<top (required)>'
  /dev/shm/lashtmp/gollum/lib/gollum.rb:8:in `require'
  /dev/shm/lashtmp/gollum/lib/gollum.rb:8:in `<top (required)>'
  /dev/shm/lashtmp/gollum/bin/gollum:7:in `require'
  /dev/shm/lashtmp/gollum/bin/gollum:7:in `<top (required)>'
gollum $ bundle --version
Bundler version 2.1.4
gollum $ rub
rubberband  ruby        
gollum $ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
gollum $ git rev-parse HEAD
986a76cf8e49102c8664271d4797c285a8a92e37

```

Tried to `bundle add github` (which seemed to include an entry called "markup") but didn't help.

Sorry if it's something obvious, I don't know anything about ruby infrastructure.

**Comment by dometto** [comment]
Just follow [these instructions](https://github.com/gollum/gollum#running-from-source) please.

**Comment by nolash** [comment]
@dometto that is what I did

**Comment by dometto** [comment]
You're doing `./bin/gollum`. The instructions say to run `bundle exec gollum`

**Comment by nolash** [comment]
yeah but a bit further down in the clip I do just that. Sorry. I thought I'd just add that too because it seemed to more clearly show the dependency that seems to be missing.

**Comment by dometto** [comment]
Did you run `bundle install`? Even if so, try doing that again.

**Comment by dometto** [comment]
> yeah but a bit further down in the clip I do just that

It looks like you're doing `bundle exec ./bin/gollum` rather than the `bundle exec bin/gollum` in the instructions. Not sure that's a huge deal and the `bundle install` should be more pertinent, but just for accuracy.

**Comment by dometto** [comment]
If it still doesn't work, please include the output of `bundle list`.

**Comment by nolash** [comment]
Doesnt work:

```
$ bundle list
Gems included by the bundle:
  * activesupport (6.0.3.2)
  * ansi (1.5.0)
  * backports (3.18.2)
  * builder (3.2.4)
  * camertron-eprun (1.1.1)
  * cldr-plurals-runtime-rb (1.0.1)
  * concurrent-ruby (1.1.7)
  * crass (1.0.6)
  * execjs (2.7.0)
  * ffi (1.13.1)
  * gemojione (4.3.3)
  * github-markup (3.0.4)
  * gollum (5.1.1)
  * gollum-lib (5.0.5)
  * gollum-rugged_adapter (1.0)
  * i18n (1.8.5)
  * json (2.3.1)
  * kramdown (2.3.0)
  * kramdown-parser-gfm (1.0.1)
  * loofah (2.7.0)
  * metaclass (0.0.4)
  * mime-types (3.3.1)
  * mime-types-data (3.2020.0512)
  * mini_portile2 (2.4.0)
  * minitest (5.14.1)
  * minitest-reporters (1.3.8)
  * mocha (1.8.0)
  * multi_json (1.15.0)
  * mustache (0.99.8)
  * mustermann (1.1.1)
  * nokogiri (1.10.10)
  * octicons (8.5.0)
  * power_assert (1.2.0)
  * rack (2.2.3)
  * rack-protection (2.0.8.1)
  * rack-test (0.6.3)
  * rake (12.3.3)
  * rb-fsevent (0.10.4)
  * rb-inotify (0.10.1)
  * rexml (3.2.4)
  * rouge (3.22.0)
  * rss (0.2.9)
  * ruby-progressbar (1.10.1)
  * ruby2_keywords (0.0.2)
  * rugged (0.99.0)
  * sass (3.7.4)
  * sass-listen (4.0.0)
  * shoulda (3.6.0)
  * shoulda-context (1.2.2)
  * shoulda-matchers (3.1.3)
  * sinatra (2.0.8.1)
  * sinatra-contrib (2.0.8.1)
  * sprockets (3.7.2)
  * sprockets-helpers (1.3.0)
  * test-unit (3.3.6)
  * therubyrhino (2.1.2)
  * therubyrhino_jar (1.7.8)
  * thread_safe (0.3.6)
  * tilt (2.0.10)
  * twitter-text (1.14.7)
  * twitter_cldr (3.2.1)
  * tzinfo (1.2.7)
  * uglifier (3.2.0)
  * unf (0.1.4)
  * unf_ext (0.0.7.7)
  * useragent (0.16.10)
  * webrick (1.4.2)
  * zeitwerk (2.4.0)
```

**Comment by nolash** [comment]
@dometto was this ticket abandoned?

**Comment by dometto** [comment]
Sorry, this seems like an issue with your ruby/rubygems installation. Ruby is complaining that it cannot require `rdoc`. I first thought that was due to an incomplete `bundle install`, but just recalled that `rdoc` is not actually a gem -- that's why it doesn't show up in your `bundle list`. Instead, `rdoc` should be part of the ruby standard library/distribution. I don't really know how to help with that, other than suggesting you somehow re-install ruby on your system. Or maybe there is a package for your OS's package manager of choice that still needs to be installed for `rdoc`?

(To make sure the problem is that `rdoc` is not installed, try opening an interactive ruby prompt with `irb` and typing `require 'rdoc'` -- my guess is you'll get the same error as when you try to run gollum)
