### ISSUE TITLE
Post-commit hook ArgumentError when running with with Ruby 3.0

### ISSUE THREAD

**Issue by kalebo** [gollum/gollum#1655]
**Describe the bug**
I get the following error when I try to edit a page with a with post-commit hook (as detailed [here](https://github.com/gollum/gollum-lib/issues/12#issuecomment-438063100)):
```
2021-01-08 22:51:33 - ArgumentError - wrong number of arguments (given 2, expected 0..1):
        /usr/local/bundle/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:319:in `fetch'
        /usr/local/bundle/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:319:in `pull'
        /config.rb:4:in `block in <top (required)>'
        /usr/local/bundle/gems/gollum-lib-5.0.6/lib/gollum-lib/hook.rb:28:in `block in execute'
        /usr/local/bundle/gems/gollum-lib-5.0.6/lib/gollum-lib/hook.rb:27:in `each_value'
        /usr/local/bundle/gems/gollum-lib-5.0.6/lib/gollum-lib/hook.rb:27:in `execute'
        /usr/local/bundle/gems/gollum-lib-5.0.6/lib/gollum-lib/committer.rb:131:in `commit'
        /usr/local/bundle/gems/gollum-5.1.2/lib/gollum/app.rb:337:in `block (2 levels) in <class:App>'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
        /usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
        /usr/local/bundle/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
        /usr/local/bundle/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
        /usr/local/bundle/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
        /usr/local/bundle/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
```

**To Reproduce**
1. make the following files:

Dockerfile:
```Dockerfile
FROM ruby:3.0 # Although on dockerhub the 3.0 label is currently the default so you only really need FROM ruby

RUN apt-get -y update && apt-get -y install libicu-dev cmake git && rm -rf /var/lib/apt/lists/*

RUN gem install github-linguist
RUN gem install gollum
RUN gem install org-ruby
RUN gem install wikicloth
RUN gem install webrick

COPY config.rb /config.rb

COPY id_rsa /root/.ssh/id_rsa
COPY id_rsa.pub /root/.ssh/id_rsa.pub
RUN ssh-keyscan gitlab.com > /root/.ssh/known_hosts

WORKDIR /wiki
ENTRYPOINT ["gollum", "--allow-uploads", "page", "--critic-markup", "--mathjax", "--config", "/config.rb", "--port", "80"]

EXPOSE 80
```
config.rb:
```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
     committer.wiki.repo.git.pull('origin', committer.wiki.ref)
     committer.wiki.repo.git.push('origin', committer.wiki.ref)
    #`cd /wiki && git pull` 
    #`cd /wiki && git push`
end
```
 * Note that the above still will cause an unsupported network url error at least on the above setup as described [here](https://github.com/gollum/gollum-lib/issues/12#issuecomment-650862728). I have to shell out and call git directly to get it to work as shown in the commented out code, but this might merit its own issue unless it's something stupidly simple.
 
deploy.sh:
```sh
#!/usr/bin/env bash

NAME=gollum-wiki
PORT=7793


if [ ! -f ./id_rsa ] || [ ! -f ./id_rsa.pub ]; then
    echo "Private and public sshkeys key needed: id_rsa, id_rsa.pub"
    exit 1
fi

docker stop "${NAME}1"
if docker build -t "$NAME" . ; then
    docker rm "${NAME}1"
    docker run --restart=unless-stopped -d --name "${NAME}1" --volume `realpath wiki`:/wiki -p $PORT:80 "$NAME"
fi
```
2. Set the executable bit on `deploy.sh` and run it. 
3. Then connect to the instance and try to edit a page. It should report an internal server error. 
4. The error can be inspected by running `docker logs --follow gollum-wiki1`. The output should match the error at the beginning of this issue.

**Expected behavior**
No failure when trying to edit pages, or at least clearly documented versions of ruby that are supported. I edited one spot on the wiki to reflect that 2.7 was needed to get around this issue, but there's probably other places this should be noted if it can't be fixed to be compatible with ruby 3.0

**Environment Info**
```
Gollum 5.1.2
Running on: x86_64-linux with Ruby version 3.0.0
Using:
rugged 0.99.0
gollum-rugged_adapter 1.0
gollum-lib 5.0.6
Markdown rendering gem: kramdown
Other renderering gems:
org-ruby 0.9.12
wikicloth 0.8.3
```

**Comment by dometto** [comment]
> Note that the above still will cause an unsupported network url error at least on the above setup as described here. I have to shell out and call git directly to get it to work as shown in the commented out code, but this might merit its own issue unless it's something stupidly simple.

I'm a little confused. The backtrace you include shows that `committer.wiki.repo.git.pull` is being called (and is throwing the error). Does the bug on ruby 3.0 persist when you replace the code inside the hook with the commented out direct calls to git?

It shouldn't have to be necessary to shell out to git, but I'm just trying to untangle the issues here.

**Comment by dometto** [comment]
Ruby 3.0 support now available by running `gem update gollum-rugged_adapter` (`v1.1` of that gem or higher required).
