### ISSUE TITLE
Docker- "Rugged::RepositoryError - could not find repository from '/wiki'"

### ISSUE THREAD

**Issue by littlediobolic** [gollum/gollum#1716]
EDIT: This appears to be an issue with the official version of the image as well. Tested the prebuilt image from docker hub on my laptop and the same issue persists.

Attempting to build the docker image on a Raspberry Pi. Used both the Dockerfile in the wiki and the official Dockerfile. They compile successfully, but loading the page after starting the container provides the following error:

```
2021-04-29 15:25:56 - Rugged::RepositoryError - could not find repository from '/wiki':
	/usr/local/bundle/gems/gollum-rugged_adapter-1.1/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
	/usr/local/bundle/gems/gollum-rugged_adapter-1.1/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
	/usr/local/bundle/gems/gollum-lib-5.1/lib/gollum-lib/git_access.rb:16:in `new'
	/usr/local/bundle/gems/gollum-lib-5.1/lib/gollum-lib/git_access.rb:16:in `initialize'
	/usr/local/bundle/gems/gollum-lib-5.1/lib/gollum-lib/wiki.rb:127:in `new'
	/usr/local/bundle/gems/gollum-lib-5.1/lib/gollum-lib/wiki.rb:127:in `initialize'
	/usr/local/bundle/gems/gollum-5.2.3/lib/gollum/app.rb:661:in `new'
	/usr/local/bundle/gems/gollum-5.2.3/lib/gollum/app.rb:661:in `wiki_new'
	/usr/local/bundle/gems/gollum-5.2.3/lib/gollum/app.rb:137:in `block in <class:App>'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/usr/local/bundle/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/usr/local/bundle/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/usr/local/bundle/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
	/usr/local/bundle/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
	/usr/local/bundle/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
192.168.3.78 - - [29/Apr/2021:15:25:56 UTC] "GET / HTTP/1.1" 500 146457
- -> /
```

Copy of the current setup of my Dockerfile:
```dockerfile
ARG BASE_IMAGE=ruby:2.7

FROM ${BASE_IMAGE}

RUN apt-get -y update \
    && apt-get -y install libicu-dev cmake \
    && rm -rf /var/lib/apt/lists/*

RUN gem install therubyracer gollum

RUN apt-get -y purge libicu-dev cmake

VOLUME /wiki

WORKDIR /wiki

RUN git init

ENTRYPOINT ["gollum"]
```
Have tried using both this command: `docker run -p 80:4567 gollum` and this docker-compose:
```yaml
version: "3.4"
services:
    gollum:
      container_name: gollum
      image: gollum
      restart: unless-stopped
      volumes:
        - /home/pi/gollum:/wiki # config files
      ports:
        - 80:80

```

**Environment Info**
Using Docker version 20.10.6, build 370c289

**Comment by littlediobolic** [comment]
Solved: Even though I thought I did, my directory I was attaching to was not initialized by git. re-initialized and all is working now.
