### ISSUE TITLE
500 error on drag&drop

### ISSUE THREAD

**Issue by biolds** [gollum/gollum#1953]
**To Reproduce**
On Gollum installed with `gem install gollum` on a Debian, the drag & drop of an image in the editor's text box triggers a 500 error :

```
Mar 08 19:38:21 gollum gollum[69]: 2023-03-08 19:38:21 - TypeError - no implicit conversion of Symbol into Integer:
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/gollum-5.3.0/lib/gollum/app.rb:239:in `[]'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/gollum-5.3.0/lib/gollum/app.rb:239:in `block (2 levels) in <class:App>'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `block in compile!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1049:in `route_eval'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1078:in `block in process_route'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `catch'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `process_route'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1028:in `block in route!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `each'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `route!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1147:in `block in dispatch!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1142:in `dispatch!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `block in call!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `call!'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:945:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/xss_header.rb:18:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/path_traversal.rb:16:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/json_csrf.rb:26:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/base.rb:50:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/base.rb:50:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-protection-2.2.4/lib/rack/protection/frame_options.rb:31:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-2.2.6.3/lib/rack/null_logger.rb:11:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-2.2.6.3/lib/rack/head.rb:12:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/show_exceptions.rb:22:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:218:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:2004:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `block in call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1780:in `synchronize'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `call'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/rack-2.2.6.3/lib/rack/handler/webrick.rb:95:in `service'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
Mar 08 19:38:21 gollum gollum[69]:         /var/lib/gems/2.7.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
Mar 08 19:38:21 gollum gollum[69]: 192.168.125.1 - - [08/Mar/2023:19:38:21 UTC] "POST /gollum/upload_file HTTP/1.1" 500 127165
```

**Environment Info**

```
# gollum --versions
Gollum 5.3.0
Running on: x86_64-linux-gnu with Ruby version 2.7.4
Using:
rugged 1.1.1
gollum-rugged_adapter 1.1.2
gollum-lib 5.2.2
Markdown rendering gem: kramdown
Other renderering gems:
none
```

**Comment by biolds** [comment]
The problem actually triggers because I'm not dropping a file.. I was dropping an image from an other browser tab, which yields the url of the image. The ajax call posts `{"file": undefined}` which triggers the 500 error in the backend.

**Comment by benjaminwil** [comment]
Hello. Thanks for reporting this and providing the additional information about drag-and-dropping an image URL versus an image from your filesystem. 

To resolve this, we would need to ensure that URLs are an accepted `params[:file]` value at the POST route for uploading images: 
https://github.com/gollum/gollum/blob/c2e0e4635d6329c2a0512568d8dfb15127980507/lib/gollum/app.rb#L246

There may be some hidden complexity around what kinds of URLs and MIME types to accept or reject. But overall it doesn’t look like a tonne of work if anyone wanted to pick this up.

**Comment by bartkamphorst** [comment]
What would be the desired behavior for accepting a dropped URL?

**Comment by benjaminwil** [comment]
I think, at least, we should handle the error gracefully instead of throwing a 500.

It would be nice to upload the file, but that requires opening it and validating it. And, unfortunately, this is maybe a can-of-worms security issue not worth venturing down.

A visual error message for the user would at least tell them they need to upload a file, not a URL.

**Comment by bartkamphorst** [comment]
But if it's a valid URL, we could also dump it into the text editor perhaps? Either as text or possibly even as a link?

**Comment by benjaminwil** [comment]
I like that. If we can return early from the existing drag-and-drop endpoint and just dump into the text editor, that seems like a great (and easy, not confusing for anyone) way forward.

**Comment by bartkamphorst** [comment]
This issue has been resolved on `master`.
