### ISSUE TITLE
gollum-auth doesn't work with v6

### ISSUE THREAD

**Issue by vadz** [gollum/gollum#2073]
I'm currently using v5.3 with gollum-auth and some custom code in `.ru` file which does something very similar to the [snippet in its README](https://github.com/bjoernalbers/gollum-auth?tab=readme-ov-file#usage), but am trying to update to v6 as I'd like to use Mermaid.

Unfortunately just `use Gollum::Auth` seems to break things in a rather weird way. First of all, [this PR](https://github.com/bjoernalbers/gollum-auth/pull/7) needs to be applied to fix a problem with an incompatible change Rack 3, but then any attempt to load any page results in an error about calling `match?` on an array of week days in `lib/gollum/views/helpers/locale_helpers.rb`, see the full stack trace below.

<details>
<summary>Full stack trace</summary>

```
NoMethodError - undefined method `match?' for ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]:Array

i18n_value.match?(YAML_VARIABLE_REGEXP)
          ^^^^^^^:
lib/gollum/views/helpers/locale_helpers.rb:68:in `has_arguments?'
lib/gollum/views/helpers/locale_helpers.rb:43:in `block in autofill'
lib/gollum/views/helpers/locale_helpers.rb:40:in `each'
lib/gollum/views/helpers/locale_helpers.rb:40:in `map'
lib/gollum/views/helpers/locale_helpers.rb:40:in `autofill'
lib/gollum/views/helpers/locale_helpers.rb:42:in `block in autofill'
lib/gollum/views/helpers/locale_helpers.rb:40:in `each'
lib/gollum/views/helpers/locale_helpers.rb:40:in `map'
lib/gollum/views/helpers/locale_helpers.rb:40:in `autofill'
lib/gollum/views/helpers/locale_helpers.rb:28:in `tt'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:148:in `call'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:148:in `find'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:116:in `block in fetch'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:112:in `each'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:112:in `fetch'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:94:in `[]'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/template.rb:46:in `render'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/template.rb:44:in `render'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/context.rb:34:in `partial'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/template.rb:44:in `render'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache/template.rb:44:in `render'
vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib/mustache.rb:133:in `render'
vendor/bundle/ruby/3.1.0/gems/mustache-sinatra-2.0.0/lib/mustache/sinatra/helpers.rb:63:in `mustache'
lib/gollum/app.rb:663:in `show_page_or_file'
lib/gollum/app.rb:614:in `block in <class:App>'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1804:in `block in compile!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (3 levels) in route!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1089:in `route_eval'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1071:in `block (2 levels) in route!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1120:in `block in process_route'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `catch'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1118:in `process_route'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1069:in `block in route!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `each'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1066:in `route!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1190:in `block in dispatch!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1185:in `dispatch!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `block in call!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `catch'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1161:in `invoke'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1001:in `call!'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:990:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/null_logger.rb:13:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/head.rb:15:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/show_exceptions.rb:23:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:224:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:2115:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `block in call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1890:in `synchronize'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:1674:in `call'
gollum-auth/lib/gollum/auth.rb:31:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/tempfile_reaper.rb:20:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/lint.rb:66:in `response'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/lint.rb:41:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/common_logger.rb:43:in `call'
vendor/bundle/ruby/3.1.0/gems/sinatra-4.0.0/lib/sinatra/base.rb:266:in `call'
vendor/bundle/ruby/3.1.0/gems/rack-3.1.7/lib/rack/content_length.rb:20:in `call'
vendor/bundle/ruby/3.1.0/gems/rackup-2.1.0/lib/rackup/handler/webrick.rb:111:in `service'
vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```
</details>

And I just have no idea what's going on here and why does inserting gollum-auth result in this. I realize that this is not really a problem in Gollum itself, but gollum-auth seems to be unmaintained, and I hope that perhaps someone here might have an idea about how to fix this. Thanks in advance for any help!

<details>
<summary>Version information</summary>

```
$ bundle exec ./bin/gollum --versions
Gollum 6.0.1
Running on: x86_64-linux-gnu with Ruby version 3.1.2
Using:
rugged 1.7.2
gollum-rugged_adapter 3.0
gollum-lib 6.0
Markdown rendering gem: kramdown
Other rendering gems:
none
```
</details>

**Comment by vadz** [comment]
Just for the record, this diff is enough to reproduce the problem (assuming `gollum-auth` is located in the corresponding subdirectory):

```diff
diff --git a/Gemfile b/Gemfile
index 22c0f04b..7f988169 100644
--- a/Gemfile
+++ b/Gemfile
@@ -17,3 +17,5 @@ end
 gemspec
 
 gem 'rake', '~> 13.0'
+
+gem "gollum-auth", path: 'gollum-auth'
diff --git a/config.ru b/config.ru
index 48f605a4..30ebc33c 100644
--- a/config.ru
+++ b/config.ru
@@ -10,3 +10,12 @@ For more information and examples:
 =end
 
 # enter your Ruby code here ...
+
+require 'rubygems'
+require 'gollum/app'
+require 'gollum/auth' # Comment this out to make it work
+
+Precious::App.set(:gollum_path, 'test/examples/lotr.git')
+Precious::App.set(:wiki_options, {h1_title: true})
+
+run Precious::App
```

Running `bundle exec rackup` shows the error above as soon as any page (including `/Home`) is loaded.

**Comment by vadz** [comment]
It looks like there is some weird conflict between ActiveModel and Gollum as I can avoid the problem by just stopping to use the former, as in [this commit](https://github.com/vadz/gollum-auth/commit/e62bc0e755de0575603beb57fd6056b1755328a5).

I have no idea if it's the right thing to do, but it Works For Me(TM), so this can be closed, unless there is interest in finding the real cause of (and proper solution for) the problem.

**Comment by benjaminwil** [comment]
Thanks for this detective work 💯 

If `gollum-auth` has been abandoned and doesn't work for _anyone_ with Gollum 6, maybe there's still more to discuss here. Maybe that turns into additional documentation for rolling one's own HTTP basic auth for Gollum 6. I don't know.

The Gollum Wiki still links out to `gollum-auth` without any caveats. Maybe that should be changed, at least.

**Comment by vadz** [comment]
BTW, I've just found, by accident, that the same error was apparently reported before in #1853 too.

**Comment by tom-kuca** [comment]
I have the same problem after I updated gollum to 6.0. I use gollum as mounted engine in Rails 8 application. I don't use `gollum-auth`. I suspect `gollum-auth` or `actionmodel` only brings translations that break `gollum`.

The first report I got is on the entry

```yaml
date:
  abbr_day_names: [Ne, Po, Út, St, Čt, Pá, So]
```
I can "fix" the error with
```yaml
date:
  abbr_day_names: ""
 ```
 Then I get the same error on the next non-string entry. I can even make the page load if I replace or array, integers and booleans with strings  (e.g. `significant: ""`, `strip_insignificant_zeros: ""`, …)
 
 My workaround is to create a `:dummy` locale with strings from https://github.com/gollum/gollum/blob/master/lib/gollum/locales/en.yml and switch the language to `:dummy` for the wiki.

**Comment by dometto** [comment]
I've opened a discussion about support/documentation for authentication given that `gollum-auth` seems to be poorly developed here: https://github.com/gollum/gollum/discussions/2088

I'll close this issue, but am very keen to hear what everyone thinks would work in the discussion thread!
