### ISSUE TITLE
Revert fails randomly

### ISSUE THREAD

**Issue by blmarket** [gollum/gollum#363]
``` ruby
# ~*~ encoding: utf-8 ~*~
require File.expand_path(File.join(File.dirname(__FILE__), "helper"))

context "Page Reverting" do
  test "reverts single commit for a page" do
    for i in 0..1000
      @path = cloned_testpath("examples/revert.git")
      @wiki = Gollum::Wiki.new(@path)
      page1 = @wiki.page('B')
      sha   = @wiki.revert_page(page1, '7c45b5f16ff3bae2a0063191ef832701214d4df5')
      page2 = @wiki.page('B')
      assert_equal sha,       page2.version.sha
      assert_equal "INITIAL", body=page2.raw_data.strip
      assert_equal body, File.read(File.join(@path, "B.md")).strip
      FileUtils.rm_rf(@path)
    end
  end
end
```

test fails on master sometimes. lol

I wanna say 'let's go xxxxing rugged! I really hate to crawl xxxxing deprecated library'

error

```
MBA:gollum blmarket$ bundle exec rake
/opt/local/bin/ruby -I"lib:lib:test:." -I"/opt/local/lib/ruby1.9/1.9.1" "/opt/local/lib/ruby1.9/1.9.1/rake/rake_test_loader.rb" "test/**/test_*.rb" 
Run options: 

# Running tests:

..................................................................................................................E....................................................

Finished tests in 71.031394s, 2.3511 tests/s, 46.1627 assertions/s.

  1) Error:
test_reverts_single_commit_for_a_page(#<Class:0x007f9324f49c78>):
NoMethodError: undefined method `version' for nil:NilClass
    /Users/blmarket/Projects/gollum/test/test_loop.rb:12:in `block (3 levels) in <top (required)>'
    /Users/blmarket/Projects/gollum/test/test_loop.rb:6:in `each'
    /Users/blmarket/Projects/gollum/test/test_loop.rb:6:in `block (2 levels) in <top (required)>'
    /opt/local/lib/ruby1.9/gems/1.9.1/gems/mocha-0.11.4/lib/mocha/integration/mini_test/version_230_to_262.rb:28:in `run'

167 tests, 3279 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [/opt/local/bin/ruby -I"lib:lib:test:." -I"...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by dometto** [comment]
I am going to close this as a nofix since it's a grit-issue, and noone is likely to solve the underlying problems. We will move away from grit in `5.x`.
