### ISSUE TITLE
Errors when trying to install and run gollum

### ISSUE THREAD

**Issue by hussein** [gollum/gollum#512]
Hi,

I tried to install gollum gem but I got:

```
Fetching: posix-spawn-0.3.6.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /Library/Ruby/Gems/1.8 directory.
```

I tried then to run gollum and I got:

```
/Library/Ruby/Site/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find gollum (>= 0) amongst [actionmailer-3.2.0, actionpack-3.2.0, activemodel-3.2.0, activerecord-3.2.0, activeresource-3.2.0, activesupport-3.2.0, arel-3.0.0, builder-3.0.0, builder-2.1.2, bundler-1.0.21, coffee-rails-3.2.1, coffee-script-2.2.0, coffee-script-source-1.2.0, erubis-2.7.0, execjs-1.3.0, highline-1.5.1, hike-1.2.1, hoe-2.3.3, i18n-0.6.0, journey-1.0.0, jquery-rails-2.0.0, json-1.6.5, json_pure-1.4.3, mail-2.4.1, mime-types-1.17.2, multi_json-1.0.4, net-sftp-2.0.2, net-ssh-2.0.15, polyglot-0.3.3, rack-1.4.1, rack-cache-1.1, rack-ssl-1.3.2, rack-test-0.6.1, rails-3.2.0, railties-3.2.0, rake-0.9.2.2, rake-0.8.7, rdoc-3.12, rubyforge-2.0.3, rubyzip-0.9.1, sass-3.1.12, sass-rails-3.2.3, sprockets-2.1.2, sqlite3-1.3.5, thor-0.14.6, tilt-1.3.3, treetop-1.4.10, tzinfo-0.3.31, uglifier-1.2.2] (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems/dependency.rb:256:in `to_spec'
    from /Library/Ruby/Site/1.8/rubygems.rb:1208:in `gem'
    from /usr/bin/gollum:18
```

Any idea what is going wrong?

OS: OS X 10.7.4

**Comment by fyddaben** [comment]
i have the same issue. how u solve it ?
