### ISSUE TITLE
NoMethodError - undefined method `>>' for "x":String

### ISSUE THREAD

**Issue by lezh** [gollum/gollum#861]
Mac OS 10.9.4
ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
Gollum 2.0.0

I created an empty directory, ran `git init` in this directory and ran `gollum` in the same directory. When I accessed `http://0.0.0.0:4567/` the error occurred:

```
NoMethodError - undefined method `>>' for "x":String:
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:108:in `unpack_object_header_gently'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:56:in `get_raw_object'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:32:in `[]'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:84:in `block in get_raw_object_by_sha1'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in `each'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in `get_raw_object_by_sha1'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:334:in `walk_log'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:287:in `log'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:306:in `rev_list'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `block in rev_list'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
    /Library/Ruby/Gems/2.0.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `rev_list'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/git_access.rb:149:in `ref_to_sha!'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/git_access.rb:39:in `block in ref_to_sha'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/git_access.rb:206:in `get_cache'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/git_access.rb:39:in `ref_to_sha'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/git_access.rb:51:in `tree'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/wiki.rb:627:in `tree_map_for'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/page.rb:304:in `find'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/wiki.rb:183:in `page'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/frontend/app.rb:194:in `show_page_or_file'
    /Library/Ruby/Gems/2.0.0/gems/gollum-2.0.0/lib/gollum/frontend/app.rb:42:in `block in <class:App>'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
localhost - - [17/Sep/2014:21:01:54 PDT] "GET / HTTP/1.1" 500 183176
- -> /
```

**Comment by ccmcbeck** [comment]
I'm seeing this error with `gollum (3.1.2)` and `gitlab-grit (2.7.3)` on Mac
I also see it with `gollum (3.0.0)` and `gitlab-grit (2.6.5)`

**Comment by ccmcbeck** [comment]
Looks like the answer is to use `gollum-rugged-adapter` https://rubygems.org/gems/gollum-rugged_adapter instead of `gitlab-grit`.  On my Mac, i also had to `brew install cmake` then run `gollum --adapter rugged`

**Comment by bartkamphorst** [comment]
Thanks for reporting the issue @ccmcbeck . Will reopen the issue for later inspection (as we do want the grit adapter to be functional until the rugged adapter is stable and and enabled by default).

**Comment by hryamzik** [comment]
Just reproduced on ubuntu 12.04, ruby 2.2 and gollum 3.1.2 (in a vagrant box).

**Comment by bartkamphorst** [comment]
@ccmcbeck Are you on ruby 2.2 too?

**Comment by ccmcbeck** [comment]
No, I'm on 2.1.5

On Tue, Mar 17, 2015 at 1:19 AM, Bart Kamphorst <notifications@github.com>
wrote:

> @ccmcbeck <https://github.com/ccmcbeck> Are you on ruby 2.2 too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gollum/gollum/issues/861#issuecomment-82196537>.
>



-- 
Regards,
Chris Beck

**Comment by dometto** [comment]
Can't reproduce this (on OS X) with:
```
gollum (3.1.3)
gollum-grit_adapter (0.1.3)
gollum-lib (4.0.2)
gitlab-grit (2.7.3)
```
on none of the following rubies:
* ruby 2.0.0p481
* ruby 2.1.5p273 
* ruby 2.2.1p85

@ccmcbeck, @hryamzik: the version differences between these gems and the ones you were using are probably minor, nevertheless I have no clue what might be going on if updating them doesn't resolve the problem. Can you confirm whether the problem persists for you on a clean install of the gollum gem?

**Comment by hryamzik** [comment]
@dometto just take vagrant with ubuntu/precise64 virtualbox box.

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

defaultbox = "ubuntu/precise64"
box = ENV['BOX'] || defaultbox

ENV['ANSIBLE_ROLES_PATH'] = "../../roles"

Vagrant.configure(2) do |config|

  config.vm.box = box
  
  config.vm.define "gollum" do |gollum_cfg|
    gollum_cfg.vm.network "private_network", type: "dhcp"
    gollum_cfg.vm.network :forwarded_port, host: 4567, guest: 4567
    gollum_cfg.vm.provider :virtualbox do |v|
      v.name = "gollum"
    end
  end

end
```

**Comment by dometto** [comment]
Good idea, @hryamzik, thanks for the Vagrantfile :)

**Comment by dometto** [comment]
Can anyone report whether this is still an issue?

**Comment by dometto** [comment]
Cannot reproduce on `Ubuntu 16.04.5` with `gollum 4.1` and `ruby 2.3.1p112`.

**Comment by jgsuess** [comment]
I still have this issue. I am a noob on ruby. How do I get you info on my stack to reproduce?

**Comment by jgsuess** [comment]
```
jg@jg-OptiPlex-9020-AIO:~/git$ git clone git://github.com/radiant/radiant.wiki.git
Cloning into 'radiant.wiki'...
remote: Enumerating objects: 2382, done.
remote: Total 2382 (delta 0), reused 0 (delta 0), pack-reused 2382
Receiving objects: 100% (2382/2382), 435.47 KiB | 273.00 KiB/s, done.
Resolving deltas: 100% (1375/1375), done.
jg@jg-OptiPlex-9020-AIO:~/git$ cd radiant.wiki
jg@jg-OptiPlex-9020-AIO:~/git/radiant.wiki$ gollum-site generate
/var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/file_window.rb:36: warning: constant ::Fixnum is deprecated
Traceback (most recent call last):
	32: from /usr/local/bin/gollum-site:23:in `<main>'
	31: from /usr/local/bin/gollum-site:23:in `load'
	30: from /var/lib/gems/2.7.0/gems/gollum-site-0.1.12/bin/gollum-site:116:in `<top (required)>'
	29: from /var/lib/gems/2.7.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:82:in `generate'
	28: from /var/lib/gems/2.7.0/gems/gollum-site-0.1.12/lib/gollum-site/site.rb:31:in `prepare'
	27: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/repo.rb:406:in `commit'
	26: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/commit.rb:121:in `find_all'
	25: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `rev_list'
	24: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
	23: from /usr/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	22: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	21: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	20: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	19: from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	18: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
	17: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby.rb:68:in `block in rev_list'
	16: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:306:in `rev_list'
	15: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:287:in `log'
	14: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:334:in `walk_log'
	13: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:89:in `get_raw_object_by_sha1'
	12: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:743:in `initpacks'
	11: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `load_packs'
	10: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:760:in `open'
	 9: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `block in load_packs'
	 8: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:761:in `each'
	 7: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `block (2 levels) in load_packs'
	 6: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:763:in `new'
	 5: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:45:in `initialize'
	 4: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:122:in `init_pack'
	 3: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:70:in `with_idx'
	 2: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `block in init_pack'
	 1: from /var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:124:in `times'
/var/lib/gems/2.7.0/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:127:in `block (2 levels) in init_pack': pack /home/jg/git/radiant.wiki/.git/objects/pack/pack-42f6db82b21100c8f107adc013a87b3c97e184c8.pack has discontinuous index 1 (Grit::GitRuby::Internal::PackFormatError)
```

**Comment by jgsuess** [comment]
Fails on demo usecase.

**Comment by bartkamphorst** [comment]
@jgsuess The gem [gollum-site](https://github.com/dreverri/gollum-site) is a separate project not maintained by the gollum organization. You should probably create an issue there or ask on StackOverflow.
