### ISSUE TITLE
Failed to render page: undefined method `render' for GitHub::Markdown:Class

### ISSUE THREAD

**Issue by davispuh** [gollum/gollum#967]
Getting this error `Failed to render page: undefined method 'render' for GitHub::Markdown:Class`
I've no idea why this happens...
And weird thing that `GitHub::Markdown.render` works fine, but as soon as I include `gollum` it doesn't work anymore...

Here, I've test app
```ruby
require 'gollum' # commenting this out, it works fine
require 'github/markdown'

puts (GitHub::Markdown.public_methods - Object.public_methods).inspect
# will show [:render, :render_gfm, :to_html] when `gollum` not included
# but with it - [:to_html]

puts GitHub::Markdown.render('# Testing')
```

Most likely it's something with my environment, but still weird that including `gollum` it changes something, seems like some kind of monkey-patching.  Any ideas how to debug this further?

I'm using Ruby 2.2.0p0 and Nginx 1.7.9 with Phusion Passenger 5.0.0.beta2, but it happens same even if I just run this test app without rack/passenger.
Gems: gollum (3.1.2), gollum-lib (4.0.2), github-markup (1.3.1), github-markdown (0.6.8)

Here's error log
```
App 9276 stderr: NoMethodError - undefined method `render' for GitHub::Markdown:Class:
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/github-markup-1.3.1/lib/github/markup/markdown.rb:8:in `block in <class:Markdown>'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/github-markup-1.3.1/lib/github/markup/markdown.rb:44:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/github-markup-1.3.1/lib/github/markup/markdown.rb:44:in `render'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/github-markup-1.3.1/lib/github/markup.rb:23:in `render'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/filter/render.rb:6:in `extract'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/markup.rb:115:in `block in process_chain'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/markup.rb:114:in `each'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/markup.rb:114:in `process_chain'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/markup.rb:159:in `render'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-lib-4.0.2/lib/gollum-lib/page.rb:225:in `formatted_data'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-3.1.2/lib/gollum/app.rb:486:in `show_page_or_file'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-3.1.2/lib/gollum/app.rb:474:in `block in <class:App>'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/gollum-3.1.2/lib/gollum/editing_auth.rb:13:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
App 9276 stderr:        /usr/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
App 9276 stderr:        /home/passenger/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
App 9276 stderr:        /home/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:150:in `accept_and_process_next_request'
App 9276 stderr:        /home/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:111:in `main_loop'
App 9276 stderr:        /home/passenger/lib/phusion_passenger/request_handler.rb:420:in `block (3 levels) in start_threads'
```

**Comment by davispuh** [comment]
found a workaround, if I include `github/markdown` before `gollum`, it works :)
```ruby
require 'github/markdown'
require 'gollum/app'
```

**Comment by dometto** [comment]
Weird, does look like something in your local setup:
```ruby
1.9.3-p362 :001 > require "gollum"
 => true 
1.9.3-p362 :002 > require "github/markdown"
 => true 
1.9.3-p362 :003 > GitHub::Markdown.render("# Test")
 => "<h1>Test</h1>\n"
```
The only difference I can think of is that requiring gollum will first require github/markup, which will then require github/markdown. Maybe you could try re-installing the github-markup gem?

Anyway, glad you found a workaround. :)

**Comment by davispuh** [comment]
I tried it already uninstalling and reinstalling those gems: gollum, gollum-lib, github-markup, github-markdown but nothing changed and
````ruby
require 'gollum'
GitHub::Markdown.render("# Test")
```
gives same error
`test.rb:2:in '<main>': uninitialized constant GitHub::Markdown (NameError)`


really no clue why it's happening..

**Comment by davispuh** [comment]
by the way, I noticed you're testing on Ruby 1.9.3, but I've Ruby 2.2 it might be that it happens under only very specific environment conditions like Ruby version, OS, installed gems and such, might not be easy to track it down, especially when a lot of gems are used which all can have different version combinations...

**Comment by AlyBadawy** [comment]
I am using Ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14], and have the same exact problem.

**Comment by StephenZhuang** [comment]
![qq20150210-1](https://cloud.githubusercontent.com/assets/7381748/6140579/b751761e-b1d4-11e4-9d7f-3ce62ddfe06f.png)

what can i do next？

**Comment by bartkamphorst** [comment]
Interesting. On 2.2.0p0:
```
$ bundle exec ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin12.0]
$ bundle exec irb
2.2.0 :001 > require 'gollum'
 => true 
2.2.0 :002 > GitHub::Markdown.render("# Test")
NameError: uninitialized constant GitHub::Markdown
	from (irb):2
	from [...]/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :003 > require 'github/markdown'
 => true 
2.2.0 :004 > GitHub::Markdown.render("# Test")
 => "<h1>Test</h1>\n" 
```
Same behavior without bundler:
```
$ irb
2.2.0 :001 > require 'gollum'
 => true 
2.2.0 :002 > require 'github/markdown'
 => true 
2.2.0 :003 > GitHub::Markdown.render("# Test")
 => "<h1>Test</h1>\n" 
```
Gem versions:
* github-markdown (0.6.8)
* github-markup (1.3.1)
* gollum (3.1.2)
* gollum-lib (4.0.1)

**Comment by dometto** [comment]
I see [github/markup](https://github.com/github/markup/blob/master/.travis.yml) is not testing against ruby 2.0.0 yet. Perhaps the issue is with that?

**Comment by dometto** [comment]
(Or more likely a bundler issue with 2.2.0, who are also not yet testing against that version)

**Comment by AlyBadawy** [comment]
I managed to fix this problem on my computer. I found out that although I have Ruby 2.2.0p0 installed, the used gems were located under the old version 2.0 that comes normally with Mac OS X 10.10.

What I did was that I uninstalled the newer version of Ruby. (I was using rbenv). then reinstalled it again. I made sure that I use:

    $ rbenv install 2.2.0
    $ rbenv global 2.2.0
    $ rbenv shell 2.2.0

Then I installed bundler and gollum gems. 

I tested on irb as per @bartkamphorst, and it worked. then I tested on a local wiki page and also finally worked.

**Comment by dometto** [comment]
@AlyBadawy, thanks for the fix. I'm assuming this issue is due to problems with ruby 2.2.0 in combination with rbenv/rvm, then, and not with gollum code. We'll wait a while before officially supporting 2.2.0 and addit it to the Travis tests.

**Comment by davispuh** [comment]
I have this problem without using rbenv/rvm but just pure Ruby 2.2 on Arch Linux, but yeah it's most likely not gollum's fault.
